SELECT /*+ PARALLEL(AUTO) */
  NULL AS INDEX_CATALOG,
  INDEXES.OWNER AS INDEX_SCHEMA,
  INDEXES.INDEX_NAME AS INDEX_NAME,
  INDEXES.TABLE_NAME AS TABLE_NAME,
  CASE WHEN INDEXES.UNIQUENESS = 'UNIQUE' THEN 'YES' ELSE 'NO' END AS IS_UNIQUE,
  DBMS_METADATA.GET_DDL('INDEX', INDEXES.INDEX_NAME, INDEXES.OWNER) AS INDEX_DEFINITION,
  INDEXES.COMPRESSION,
  INDEXES.TABLESPACE_NAME 
FROM
  ALL_INDEXES INDEXES
WHERE
  -- REGEXP_LIKE(INDEXES.OWNER, '${schemas}')
  INDEXES.OWNER = '${schemas}'
ORDER BY
  INDEX_SCHEMA,
  TABLE_NAME,
  INDEX_NAME
