SELECT /*+ PARALLEL(AUTO) */
  NULL AS PRIMARY_KEY_CATALOG,
  PRIMARY_KEYS.OWNER AS PRIMARY_KEY_SCHEMA,
  PRIMARY_KEYS.TABLE_NAME AS PRIMARY_KEY_TABLE_NAME,
  PRIMARY_KEYS.CONSTRAINT_NAME AS PRIMARY_KEY_NAME,
  DBMS_METADATA.GET_DDL('CONSTRAINT', PRIMARY_KEYS.CONSTRAINT_NAME, PRIMARY_KEYS.OWNER) 
    AS PRIMARY_KEY_DEFINITION
FROM
  ALL_CONSTRAINTS PRIMARY_KEYS
WHERE
  -- REGEXP_LIKE(PRIMARY_KEYS.OWNER, '${schemas}')
  PRIMARY_KEYS.OWNER = '${schemas}'
  AND PRIMARY_KEYS.CONSTRAINT_TYPE = 'P'
