SELECT /*+ PARALLEL(AUTO) */
  NULL AS INDEX_CATALOG,
  INDEXES.OWNER AS INDEX_SCHEMA,
  INDEXES.INDEX_NAME AS INDEX_NAME,
  INDEXES.TABLE_NAME AS TABLE_NAME,
  INDEX_COLUMNS.COLUMN_NAME,
  INDEX_COLUMNS.COLUMN_POSITION AS ORDINAL_POSITION,
  INDEX_COLUMN_EXPRESSIONS.COLUMN_EXPRESSION AS INDEX_COLUMN_DEFINITION
FROM 
  ALL_INDEXES INDEXES
  INNER JOIN ALL_IND_COLUMNS INDEX_COLUMNS
  ON 
    INDEXES.INDEX_NAME = INDEX_COLUMNS.INDEX_NAME
    AND INDEXES.TABLE_OWNER = INDEX_COLUMNS.TABLE_OWNER
    AND INDEXES.TABLE_NAME = INDEX_COLUMNS.TABLE_NAME
    AND INDEXES.OWNER = INDEX_COLUMNS.INDEX_OWNER
  INNER JOIN ALL_IND_EXPRESSIONS INDEX_COLUMN_EXPRESSIONS
  ON 
    INDEXES.INDEX_NAME = INDEX_COLUMN_EXPRESSIONS.INDEX_NAME
    AND INDEXES.TABLE_OWNER = INDEX_COLUMN_EXPRESSIONS.TABLE_OWNER
    AND INDEXES.TABLE_NAME = INDEX_COLUMN_EXPRESSIONS.TABLE_NAME
    AND INDEXES.OWNER = INDEX_COLUMN_EXPRESSIONS.INDEX_OWNER
    AND INDEX_COLUMNS.COLUMN_POSITION = INDEX_COLUMN_EXPRESSIONS.COLUMN_POSITION    
WHERE
  -- REGEXP_LIKE(INDEXES.OWNER, '${schemas}')
  INDEXES.OWNER = '${schemas}'
ORDER BY 
  INDEX_SCHEMA,
  TABLE_NAME,
  INDEX_NAME,
  ORDINAL_POSITION
