SELECT /*+ PARALLEL(AUTO) */
  NULL AS CONSTRAINT_CATALOG,
  CONSTRAINTS.OWNER AS CONSTRAINT_SCHEMA,
  CONSTRAINTS.TABLE_NAME,
  CONSTRAINTS.CONSTRAINT_NAME,
  DBMS_METADATA.GET_DDL('CONSTRAINT', CONSTRAINTS.CONSTRAINT_NAME, CONSTRAINTS.OWNER) 
    AS CHECK_CLAUSE
FROM
  ALL_CONSTRAINTS CONSTRAINTS
WHERE
  -- REGEXP_LIKE(CONSTRAINTS.OWNER, '${schemas}')
  CONSTRAINTS.OWNER = '${schemas}'
  AND CONSTRAINT_TYPE IN ('C', 'U')