SELECT /*+ PARALLEL(AUTO) */
  NULL AS TABLE_CATALOG,
  TABLES.OWNER AS TABLE_SCHEMA,
  TABLES.TABLE_NAME,
  DBMS_METADATA.GET_DDL('TABLE', TABLES.TABLE_NAME, TABLES.OWNER) 
    AS TABLE_DEFINITION
FROM
  ALL_TABLES TABLES
WHERE
  -- REGEXP_LIKE(TABLES.OWNER, '${schemas}')
  TABLES.OWNER = '${schemas}'
ORDER BY
  TABLE_SCHEMA,
  TABLE_NAME
