SELECT /*+ PARALLEL(AUTO) */
  NULL AS FOREIGN_KEY_CATALOG,
  FOREIGN_KEYS.OWNER AS FOREIGN_KEY_SCHEMA,
  FOREIGN_KEYS.TABLE_NAME AS FOREIGN_KEY_TABLE_NAME,  
  FOREIGN_KEYS.CONSTRAINT_NAME AS FOREIGN_KEY_NAME,
  DBMS_METADATA.GET_DDL('REF_CONSTRAINT', FOREIGN_KEYS.CONSTRAINT_NAME, FOREIGN_KEYS.OWNER) 
    AS FOREIGN_KEY_DEFINITION
FROM
  ALL_CONSTRAINTS FOREIGN_KEYS
WHERE
  -- REGEXP_LIKE(FOREIGN_KEYS.OWNER, '${schemas}')
  FOREIGN_KEYS.OWNER = '${schemas}'
  AND FOREIGN_KEYS.CONSTRAINT_TYPE = 'R'
