SELECT /*+ PARALLEL(AUTO) */
  NULL AS TABLE_CAT,
  PRIMARY_KEYS.OWNER AS TABLE_SCHEM,
  PRIMARY_KEYS.TABLE_NAME,
  PRIMARY_KEYS.CONSTRAINT_NAME AS PK_NAME,
  PK_COLUMNS.COLUMN_POSITION AS KEY_SEQ,
  PK_COLUMNS.COLUMN_NAME
FROM 
  ALL_CONSTRAINTS PRIMARY_KEYS
  INNER JOIN ALL_IND_COLUMNS PK_COLUMNS
  ON 
    PRIMARY_KEYS.CONSTRAINT_NAME = PK_COLUMNS.INDEX_NAME
    AND PRIMARY_KEYS.OWNER = PK_COLUMNS.TABLE_OWNER
    AND PRIMARY_KEYS.TABLE_NAME = PK_COLUMNS.TABLE_NAME
    AND PRIMARY_KEYS.OWNER = PK_COLUMNS.INDEX_OWNER
WHERE
  -- REGEXP_LIKE(PRIMARY_KEYS.OWNER, '${schemas}')
  PRIMARY_KEYS.OWNER = '${schemas}'
  AND PRIMARY_KEYS.CONSTRAINT_TYPE = 'P'
ORDER BY 
  TABLE_SCHEM,
  TABLE_NAME,
  PK_NAME,
  KEY_SEQ
