SELECT /*+ PARALLEL(AUTO) */
  NULL AS CONSTRAINT_CATALOG,
  CONSTRAINTS.OWNER AS CONSTRAINT_SCHEMA,
  CONSTRAINTS.CONSTRAINT_NAME,
  NULL AS TABLE_CATALOG,
  CONSTRAINTS.OWNER AS TABLE_SCHEMA,
  CONSTRAINTS.TABLE_NAME,
  CASE CONSTRAINTS.CONSTRAINT_TYPE WHEN 'C' THEN 'CHECK' WHEN 'U' THEN 'UNIQUE' WHEN 'P' THEN 'PRIMARY KEY' WHEN 'R' THEN 'FOREIGN KEY' END 
    AS CONSTRAINT_TYPE,
  CASE WHEN CONSTRAINTS.DEFERRABLE = 'NOT DEFERRABLE' THEN 'N' ELSE 'Y' END 
    AS IS_DEFERRABLE,
  CASE WHEN CONSTRAINTS.DEFERRED = 'IMMEDIATE' THEN 'N' ELSE 'Y' END 
    AS INITIALLY_DEFERRED
FROM
  ALL_CONSTRAINTS CONSTRAINTS
WHERE
  -- REGEXP_LIKE(CONSTRAINTS.OWNER, '${schemas}')
  CONSTRAINTS.OWNER = '${schemas}'
  AND CONSTRAINT_TYPE IN ('C', 'U', 'P', 'R')
