SELECT /*+ PARALLEL(AUTO) */
  NULL AS TABLE_CATALOG,
  VIEWS.OWNER AS TABLE_SCHEMA,
  VIEWS.VIEW_NAME AS TABLE_NAME,
  VIEWS.TEXT AS VIEW_DEFINITION,
  'UNKNOWN' AS CHECK_OPTION,
  CASE WHEN VIEWS.READ_ONLY = 'N' THEN 'Y' ELSE 'N' END AS IS_UPDATABLE
FROM
  ALL_VIEWS VIEWS
WHERE
  -- REGEXP_LIKE(VIEWS.OWNER, '${schemas}')
  VIEWS.OWNER = '${schemas}'
ORDER BY
  TABLE_SCHEMA,
  TABLE_NAME
